version: '2'

services:
  postgres:
    image: 'postgres:12.2'
    environment:
      POSTGRES_USER: 'mobydock'
      POSTGRES_PASSWORD: 'yourpassword'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:5.0.8'
    volumes:
      - 'redis:/data'

  mobydock:
    build: '.'
    command: gunicorn -b 0.0.0.0:8000 --reload "mobydock.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'

volumes:
  postgres: {}
  redis: {}
